FROM python:3.11-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app.py .

EXPOSE 5000

# Timeout if db cluster is not up fast enough... 
CMD ["gunicorn", "--bind", "0.0.0.0:5000", "--timeout", "120", "app:app"] 